version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      -"6432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
