version: '3.9'

services:
  pg:
    image: postgres:latest
    container_name: pg
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5433:5432"
    hostname: 127.0.0.1
    volumes:
      - pgdata:/var/lib/postgresql/data  # Mount a volume for persistence

volumes:
  pgdata:
