// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: cv.proto

package cv_backend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Intro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos         string `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`                                    // Position title
	Email       string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                // Email address
	MobilePhone string `protobuf:"bytes,4,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone,omitempty"` // Corrected typo
	Address     string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`                            // Physical address
	Summary     string `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`                            // Professional summary
}

func (x *Intro) Reset() {
	*x = Intro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Intro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intro) ProtoMessage() {}

func (x *Intro) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intro.ProtoReflect.Descriptor instead.
func (*Intro) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{0}
}

func (x *Intro) GetPos() string {
	if x != nil {
		return x.Pos
	}
	return ""
}

func (x *Intro) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Intro) GetMobilePhone() string {
	if x != nil {
		return x.MobilePhone
	}
	return ""
}

func (x *Intro) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Intro) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type WorkExperience struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyName string      `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"` // Company name
	Role        string      `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                                  // Role/Position at company
	Description string      `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                    // Brief description of the job
	StartDate   string      `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`       // Start date in YYYY-MM format
	EndDate     string      `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`             // End date (or empty if current)
	WorkDesc    []*WorkDesc `protobuf:"bytes,7,rep,name=work_desc,json=workDesc,proto3" json:"work_desc,omitempty"`          // List of detailed work descriptions
}

func (x *WorkExperience) Reset() {
	*x = WorkExperience{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkExperience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkExperience) ProtoMessage() {}

func (x *WorkExperience) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkExperience.ProtoReflect.Descriptor instead.
func (*WorkExperience) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{1}
}

func (x *WorkExperience) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *WorkExperience) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkExperience) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkExperience) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *WorkExperience) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *WorkExperience) GetWorkDesc() []*WorkDesc {
	if x != nil {
		return x.WorkDesc
	}
	return nil
}

type WorkDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Detailed description of work responsibility
}

func (x *WorkDesc) Reset() {
	*x = WorkDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkDesc) ProtoMessage() {}

func (x *WorkDesc) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkDesc.ProtoReflect.Descriptor instead.
func (*WorkDesc) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{2}
}

func (x *WorkDesc) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Education struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchoolName string `protobuf:"bytes,2,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"` // Name of the school or institution
	Degree     string `protobuf:"bytes,3,opt,name=degree,proto3" json:"degree,omitempty"`                           // Degree obtained
	Field      string `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"`                             // Field of study
	StartDate  string `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`    // Start date in YYYY-MM format
	EndDate    string `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`          // End date in YYYY-MM format
}

func (x *Education) Reset() {
	*x = Education{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{3}
}

func (x *Education) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

func (x *Education) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *Education) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Education) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Education) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type Skill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillName string `protobuf:"bytes,2,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"` // Name of the skill
}

func (x *Skill) Reset() {
	*x = Skill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{4}
}

func (x *Skill) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

type CV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Intro       *Intro            `protobuf:"bytes,2,opt,name=intro,proto3" json:"intro,omitempty"`             // Introduction section
	Experiences []*WorkExperience `protobuf:"bytes,3,rep,name=experiences,proto3" json:"experiences,omitempty"` // List of work experiences
	Education   []*Education      `protobuf:"bytes,4,rep,name=education,proto3" json:"education,omitempty"`     // List of education entries
	Skills      []*Skill          `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`           // List of skills
}

func (x *CV) Reset() {
	*x = CV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CV) ProtoMessage() {}

func (x *CV) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CV.ProtoReflect.Descriptor instead.
func (*CV) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{5}
}

func (x *CV) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CV) GetIntro() *Intro {
	if x != nil {
		return x.Intro
	}
	return nil
}

func (x *CV) GetExperiences() []*WorkExperience {
	if x != nil {
		return x.Experiences
	}
	return nil
}

func (x *CV) GetEducation() []*Education {
	if x != nil {
		return x.Education
	}
	return nil
}

func (x *CV) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type CreateCVReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cv *CV `protobuf:"bytes,1,opt,name=cv,proto3" json:"cv,omitempty"` // CV data
}

func (x *CreateCVReq) Reset() {
	*x = CreateCVReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCVReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCVReq) ProtoMessage() {}

func (x *CreateCVReq) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCVReq.ProtoReflect.Descriptor instead.
func (*CreateCVReq) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCVReq) GetCv() *CV {
	if x != nil {
		return x.Cv
	}
	return nil
}

type CreateCVRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the newly created CV
}

func (x *CreateCVRes) Reset() {
	*x = CreateCVRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCVRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCVRes) ProtoMessage() {}

func (x *CreateCVRes) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCVRes.ProtoReflect.Descriptor instead.
func (*CreateCVRes) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCVRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCVReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the requested CV
}

func (x *GetCVReq) Reset() {
	*x = GetCVReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCVReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCVReq) ProtoMessage() {}

func (x *GetCVReq) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCVReq.ProtoReflect.Descriptor instead.
func (*GetCVReq) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{8}
}

func (x *GetCVReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCVRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cv *CV `protobuf:"bytes,1,opt,name=cv,proto3" json:"cv,omitempty"` // CV data
}

func (x *GetCVRes) Reset() {
	*x = GetCVRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCVRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCVRes) ProtoMessage() {}

func (x *GetCVRes) ProtoReflect() protoreflect.Message {
	mi := &file_cv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCVRes.ProtoReflect.Descriptor instead.
func (*GetCVRes) Descriptor() ([]byte, []int) {
	return file_cv_proto_rawDescGZIP(), []int{9}
}

func (x *GetCVRes) GetCv() *CV {
	if x != nil {
		return x.Cv
	}
	return nil
}

var File_cv_proto protoreflect.FileDescriptor

var file_cv_proto_rawDesc = []byte{
	0x0a, 0x08, 0x63, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x05, 0x49,
	0x6e, 0x74, 0x72, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x22, 0xcb, 0x01, 0x0a, 0x0e, 0x57, 0x6f, 0x72, 0x6b, 0x45, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x77, 0x6f, 0x72,
	0x6b, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x65, 0x73,
	0x63, 0x22, 0x2c, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x94, 0x01, 0x0a, 0x09, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x26, 0x0a, 0x05, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xaf,
	0x01, 0x0a, 0x02, 0x43, 0x56, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x52, 0x05, 0x69, 0x6e,
	0x74, 0x72, 0x6f, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x45,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x72,
	0x69, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x64, 0x75, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1e, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x06, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73,
	0x22, 0x22, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x56, 0x52, 0x65, 0x71, 0x12,
	0x13, 0x0a, 0x02, 0x63, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x03, 0x2e, 0x43, 0x56,
	0x52, 0x02, 0x63, 0x76, 0x22, 0x1d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x56,
	0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x56, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x1f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x56, 0x52, 0x65, 0x73, 0x12, 0x13, 0x0a, 0x02, 0x63,
	0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x03, 0x2e, 0x43, 0x56, 0x52, 0x02, 0x63, 0x76,
	0x32, 0x52, 0x0a, 0x09, 0x43, 0x56, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a,
	0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x56, 0x12, 0x0c, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x56, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x56, 0x52, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x43, 0x56, 0x12, 0x09,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x56, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x56, 0x52, 0x65, 0x73, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x70, 0x61, 0x6b, 0x6f, 0x72, 0x6e, 0x73, 0x6b, 0x2f, 0x63, 0x76,
	0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cv_proto_rawDescOnce sync.Once
	file_cv_proto_rawDescData = file_cv_proto_rawDesc
)

func file_cv_proto_rawDescGZIP() []byte {
	file_cv_proto_rawDescOnce.Do(func() {
		file_cv_proto_rawDescData = protoimpl.X.CompressGZIP(file_cv_proto_rawDescData)
	})
	return file_cv_proto_rawDescData
}

var file_cv_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cv_proto_goTypes = []any{
	(*Intro)(nil),          // 0: Intro
	(*WorkExperience)(nil), // 1: WorkExperience
	(*WorkDesc)(nil),       // 2: WorkDesc
	(*Education)(nil),      // 3: Education
	(*Skill)(nil),          // 4: Skill
	(*CV)(nil),             // 5: CV
	(*CreateCVReq)(nil),    // 6: CreateCVReq
	(*CreateCVRes)(nil),    // 7: CreateCVRes
	(*GetCVReq)(nil),       // 8: GetCVReq
	(*GetCVRes)(nil),       // 9: GetCVRes
}
var file_cv_proto_depIdxs = []int32{
	2, // 0: WorkExperience.work_desc:type_name -> WorkDesc
	0, // 1: CV.intro:type_name -> Intro
	1, // 2: CV.experiences:type_name -> WorkExperience
	3, // 3: CV.education:type_name -> Education
	4, // 4: CV.skills:type_name -> Skill
	5, // 5: CreateCVReq.cv:type_name -> CV
	5, // 6: GetCVRes.cv:type_name -> CV
	6, // 7: CVService.CreateCV:input_type -> CreateCVReq
	8, // 8: CVService.GetCV:input_type -> GetCVReq
	7, // 9: CVService.CreateCV:output_type -> CreateCVRes
	9, // 10: CVService.GetCV:output_type -> GetCVRes
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_cv_proto_init() }
func file_cv_proto_init() {
	if File_cv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cv_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Intro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WorkExperience); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WorkDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Education); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Skill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CreateCVReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CreateCVRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetCVReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cv_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetCVRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cv_proto_goTypes,
		DependencyIndexes: file_cv_proto_depIdxs,
		MessageInfos:      file_cv_proto_msgTypes,
	}.Build()
	File_cv_proto = out.File
	file_cv_proto_rawDesc = nil
	file_cv_proto_goTypes = nil
	file_cv_proto_depIdxs = nil
}
