// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.28.2
// source: cv.proto

package cv_backend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CVService_CreateCV_FullMethodName = "/CVService/CreateCV"
	CVService_GetCV_FullMethodName    = "/CVService/GetCV"
)

// CVServiceClient is the client API for CVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CVServiceClient interface {
	CreateCV(ctx context.Context, in *CreateCVReq, opts ...grpc.CallOption) (*CreateCVRes, error)
	GetCV(ctx context.Context, in *GetCVReq, opts ...grpc.CallOption) (*GetCVRes, error)
}

type cVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCVServiceClient(cc grpc.ClientConnInterface) CVServiceClient {
	return &cVServiceClient{cc}
}

func (c *cVServiceClient) CreateCV(ctx context.Context, in *CreateCVReq, opts ...grpc.CallOption) (*CreateCVRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCVRes)
	err := c.cc.Invoke(ctx, CVService_CreateCV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cVServiceClient) GetCV(ctx context.Context, in *GetCVReq, opts ...grpc.CallOption) (*GetCVRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCVRes)
	err := c.cc.Invoke(ctx, CVService_GetCV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CVServiceServer is the server API for CVService service.
// All implementations must embed UnimplementedCVServiceServer
// for forward compatibility
type CVServiceServer interface {
	CreateCV(context.Context, *CreateCVReq) (*CreateCVRes, error)
	GetCV(context.Context, *GetCVReq) (*GetCVRes, error)
	mustEmbedUnimplementedCVServiceServer()
}

// UnimplementedCVServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCVServiceServer struct {
}

func (UnimplementedCVServiceServer) CreateCV(context.Context, *CreateCVReq) (*CreateCVRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCV not implemented")
}
func (UnimplementedCVServiceServer) GetCV(context.Context, *GetCVReq) (*GetCVRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCV not implemented")
}
func (UnimplementedCVServiceServer) mustEmbedUnimplementedCVServiceServer() {}

// UnsafeCVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CVServiceServer will
// result in compilation errors.
type UnsafeCVServiceServer interface {
	mustEmbedUnimplementedCVServiceServer()
}

func RegisterCVServiceServer(s grpc.ServiceRegistrar, srv CVServiceServer) {
	s.RegisterService(&CVService_ServiceDesc, srv)
}

func _CVService_CreateCV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCVReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CVServiceServer).CreateCV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CVService_CreateCV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CVServiceServer).CreateCV(ctx, req.(*CreateCVReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CVService_GetCV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCVReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CVServiceServer).GetCV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CVService_GetCV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CVServiceServer).GetCV(ctx, req.(*GetCVReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CVService_ServiceDesc is the grpc.ServiceDesc for CVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CVService",
	HandlerType: (*CVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCV",
			Handler:    _CVService_CreateCV_Handler,
		},
		{
			MethodName: "GetCV",
			Handler:    _CVService_GetCV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cv.proto",
}
